<a href="https://colab.research.google.com/github/donisrv/Calculator-Java-/blob/master/NumPy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
data1 = [3.5, 5, 6, 2] #list
arr1 = np.array(data1) # array1

In [ ]:
data1

[3.5, 5, 6, 2]

In [ ]:
arr1

array([3.5, 5. , 6. , 2. ])

In [ ]:
data2 = (4, 5, 3.2, 7) # tuple
arr2 = np.array(data2) 

In [ ]:
data2

(4, 5, 3.2, 7)

In [ ]:
arr2

array([4. , 5. , 3.2, 7. ])

In [ ]:
arr1.ndim # array1 ning o'lchami

1

In [ ]:
arr2.ndim # array2 ning o'lchami

1

# `**Ikki o'lchamli massivlar**`

In [ ]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] # List ichidagi list
arr3 = np.array(data3) # arra3

In [ ]:
data3, arr3

([[1, 2, 3, 4], [5, 6, 7, 8]], array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [ ]:
arr3.ndim

2

# `shape`, `size` metodlari

In [ ]:
arr3.shape # qator va ustunlar sonini korsatadi (qator, ustunlar)

(2, 4)

In [ ]:
arr3.size # array3 ning elemntlar soni

8

# N o'lchamli massivlarni yaritishni boshqa usullari

In [ ]:
arr4 = np.zeros(shape = (2, 4)) # barcha elementlari 0 ga teng (2, 4) o'lchamli massiv yaratadi 2qator 4 ustunli
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr5 = np.ones(shape = (2, 4)) # barcha elementlari 1 ga teng (2, 4) o'lchamli massiv yaratadi 2qator 4 ustunli
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

`arange` funksiyasi yordamida yaratish

In [ ]:
arr6 = np.arange(4, 20, 2) # 4 dan 20 gacha bo'lgan qiymatlarni 2 qwadam bilan massivga joylab beradi
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr7 = np.arange(20) # 0 dan 20 gacha bo'lgan qiymatlarni 1 qadam bilan massivga joylab beradi
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

`random` funksiyasi yordamida yaratish (`rand`, `randint`, `randn`)

In [ ]:
arr8 = np.random.rand(2, 4) # (2, 4) o'lchamli --> elementlar (0 ~ 1) taxminiy qiymatlardan tashkil topgan
arr8

array([[0.19907696, 0.00569369, 0.55472568, 0.15212279],
       [0.13330225, 0.4621064 , 0.93747601, 0.04442627]])

In [ ]:
arr9 = np.random.randint(5, size=(2, 4)) # (2, 4) o'lchamli va max qiymati 5 gacha bo'lgan int sonlar
arr9

array([[0, 0, 0, 3],
       [4, 4, 1, 3]])

In [ ]:
arr10 = np.random.randn(2, 4) # (2, 4) o'lchamli --> elementlari (Normal dist)
arr10 

array([[ 1.35663432e+00, -6.10493621e-01,  6.19091979e-01,
        -3.80182498e+00],
       [ 2.54691384e-01,  6.09220066e-01, -5.17659782e-05,
         1.62884358e-02]])

# `Masala(1): 1-o'lchamli massivlar yaratish`
Masala sharti : Elementlari ixtiyoriy n ta (n > 0, butun son) bo'lgan 1-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.

Yordam : array yoki random funksiyasidan foydalaning.

In [7]:
# JAVOBNI SHU YERGA YOZING
def one_dim(n):
  """ n ta elementdan tashkil topgan 1-o'lchamli massiv """  
  arr1 = np.random.rand(n)
  print(arr1)
  return arr1

In [8]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Check that function returns the correct output for several inputs"""
for i in range(1, 10):
  assert len(one_dim(i)) == i, f"n elementlar soni, funksiyada noto'g'ri qo'llanilgan" # n elementlar soni
  arr = one_dim(i) # massiv
  assert arr.ndim == 1, f"1-o'lchamli massiv aniqlanmadi"# massiv o'lchami
  assert type(arr) == np.ndarray, f"massiv aniqlanmadi" #numpy array 

[0.48094507]
[0.3480924]
[0.67071134 0.4064632 ]
[0.2586997  0.20733812]
[0.53126718 0.22838116 0.17431686]
[0.91272845 0.80599095 0.84543867]
[0.18247533 0.47338453 0.04736296 0.19526487]
[0.48539691 0.60423878 0.13890096 0.06183771]
[0.61190969 0.27082678 0.89797187 0.32266168 0.07303293]
[0.6511625  0.77384497 0.96833302 0.53728088 0.77015936]
[0.02706836 0.57170979 0.33427855 0.01859783 0.00515261 0.18748984]
[0.97059334 0.66272764 0.42358592 0.98406725 0.19787511 0.3060632 ]
[0.40709258 0.46688727 0.69553808 0.85734328 0.03536831 0.86852886
 0.18728904]
[0.41146654 0.62025817 0.45406314 0.033444   0.15900638 0.84961416
 0.82789558]
[0.69143349 0.44749215 0.26477233 0.11912981 0.43146971 0.07831265
 0.36541885 0.09826872]
[0.30316258 0.68514055 0.77025235 0.85318342 0.99523666 0.48071849
 0.60946527 0.1787589 ]
[0.76200458 0.61489174 0.15080554 0.82040366 0.34305883 0.59024417
 0.73477016 0.24864099 0.49586349]
[0.03930414 0.7700362  0.03415456 0.43829752 0.58219013 0.22019171
 0.9

# Masala(2) 2-o'lchamli massivlar yaratish
Masala : Shakli `shape(r, c)` bo'lgan 2-o'lchamli massiv (array) yaratuvchi funksiyani davom ettiring.

Yordam : numpy kutubxonasida massivlar yaratuvchi funksiyalarining istalganidan foydlanishingiz mumkin.

In [11]:
# JAVOBNI SHU YERGA YOZING
def two_dim(r, c):
    """ r ta qator, c ta ustundan tashkil topgan 2-o'lchamli massiv """  
    my_arr3 = np.random.rand(r, c) # barcha elementlari 0 ga teng (2, 4) o'lchamli massiv yaratadi 2qator 4 ustunli
    print('Shakli shape(r, c) bo\'lgan 2-o\'lchamli massiv (array) yaratuvchi funksiya natijasi\n',my_arr3,'\n')
    print('Qator va ustunlar soni', my_arr3.shape,'\n')
    print('Massiv o\'lchami',my_arr3.ndim, 'ga teng')
    return my_arr3

In [12]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Check that function returns the correct output for several inputs"""
arr = two_dim(3, 2) # massiv
assert arr.shape == (3, 2), f"funksiyada, o'lchamlar noto'g'ri qo'llanilgan" # shape
assert arr.ndim == 2, f"2-o'lchamli massiv aniqlanmadi" # massiv o'lchami
assert type(arr) == np.ndarray, f"massiv aniqlanmadi"# #numpy array 

Shakli shape(r, c) bo'lgan 2-o'lchamli massiv (array) yaratuvchi funksiya natijasi
 [[0.19930752 0.83137957]
 [0.10803183 0.58571714]
 [0.52495507 0.58017383]] 

Qator va ustunlar soni (3, 2) 

Massiv o'lchami 2 ga teng
